name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
    paths:
      - 'run.py'  # Only trigger when run.py changes (contains Dockerfile)
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Dockerfile from run.py
        run: |
          python3 -c "
          with open('run.py', 'r') as f:
              content = f.read()
              start = content.find('DOCKERFILE_CONTENT = \"\"\"') + len('DOCKERFILE_CONTENT = \"\"\"')
              end = content.find('\"\"\"', start)
              dockerfile = content[start:end]
              with open('Dockerfile', 'w') as df:
                  df.write(dockerfile)
          "

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/dbg-container
          tags: |
            type=sha,format=short
            type=ref,event=branch
            latest

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            HEAPTRACK_URL=https://github.com/KDE/heaptrack/releases/download/v1.5.0/heaptrack-1.5.0-Linux.deb